---
- name: Generate cloud-init configuration
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Create rancher-lima configuration
      ansible.builtin.template:
        src: rancher-lima.yml.j2
        dest: rancher-lima.yml
